image: node:8

stages:
  - test
  - deploy

before_script:
  - npm ci

test:
  stage: test
  script:
    - npm run lint
    - npm test
  except:
    - master

.publish: &publish
  stage: deploy
  script:
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm publish --tag $tag
  only:
    - tags
  except:
    - /^.*-alpha.*$/

publish latest:
  <<: *publish
  only:
    - tags
    - master
  variables:
    tag: latest

publish alpha:
  <<: *publish
  only:
    - /^.*-alpha.*$/
  except:
    - branches
  variables:
    tag: alpha
